import fs from 'fs'
import path from 'path'

const headerComment = `
/* -------------------------------------------------
   THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY
   Generated by: build-css.js
-------------------------------------------------- */`

const stylesDir = './src/styles'
const outputFile = 'styles.gen.css'
const outputFilePath = path.join(stylesDir, outputFile)

// main.css defines the shared :root custom properties (colours, fonts, ...)
// that every other stylesheet relies on via var(), so it must load first.
const files = fs.readdirSync(stylesDir)
  .filter(file => file.endsWith('.css') && file !== outputFile)
  .sort((a, b) => {
    if (a === 'main.css') return -1
    if (b === 'main.css') return 1
    return a.localeCompare(b)
  })

const imports = files.map(file => `@import './${file}';`).join('\n')
fs.writeFileSync(outputFilePath, `${headerComment}\n\n${imports}\n`)