import fs from 'fs'
import path from 'path'

const headerComment = `/* -------------------------------------------------
   THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY
   Generated by: build-modules.js
-------------------------------------------------- */`

const srcDir = './src/modules'
const outputFilePath = path.join(srcDir, 'modules.gen.js')

const files = fs
  .readdirSync(srcDir)
  .filter(file => file.endsWith('.js') && file !== 'units.gen.js' && !file.startsWith('_'))

const importStatements = []
const uGenAssignments = []
const moduleAssignments = []

for (const file of files) {
  const moduleName = file.replace(/\.js$/, '')
  const moduleNameUppercase = moduleName.charAt(0).toUpperCase() + moduleName.slice(1)
  const fullPath = path.join(srcDir, file)
  const content = fs.readFileSync(fullPath, 'utf-8')

  const hasDefinition = /export\s+const\s+definition\b/.test(content)
  if (!hasDefinition) continue

  const exports = [`definition as ${moduleName}_def`]
  const audioAssignments = [`definition: ${moduleName}_def`]
  const guiAssignments = [`definition: ${moduleName}_def`]

  if (/export\s+class\s+UGen\b/.test(content)) {
    exports.push(`UGen as ${moduleName}_ugen`)
    audioAssignments.push(`UGen: ${moduleName}_ugen`)
  }

  if (/export\s+class\s+Visualisation\b/.test(content)) {
    exports.push(`Visualisation as ${moduleName}_vis`)
    guiAssignments.push(`Visualisation: ${moduleName}_vis`)
  }

  importStatements.push(`import { ${exports.join(', ')} } from './${file}'`)
  uGenAssignments.push(`  ${moduleNameUppercase}: { ${audioAssignments.join(', ')} }`)
  moduleAssignments.push(`  ${moduleNameUppercase}: { ${guiAssignments.join(', ')} }`)
}

const finalOutput = [
  headerComment,
  '',
  ...importStatements,
  '',
  'export const ugens = {',
  uGenAssignments.join(',\n'),
  '}',
  '',
  'export const modules = {',
  moduleAssignments.join(',\n'),
  '}',
  ''
].join('\n')

fs.writeFileSync(outputFilePath, finalOutput)
